### ISSUE TITLE
no command to make stuff?

### ISSUE THREAD

**Issue by Bucky420** [Sinhika/Ruins#1]
i don't see how u can use this for minecraft as u need to use schematics i don't know what kind of system but it seems u have to type out one block at a time lol ... that sounds like hell to me

**Comment by Sinhika** [comment]
This is my personal stash of templates to use with the Ruins mod, updated from really ancient versions to the newer format used for Ruins in 1.10 or so. I just put it up for any other Ruins users who were interested in some of the old templates that never got updated.
